kind: pipeline
name: publish
type: docker

steps:
  - name: create settings.xml
    image: md5lukas/drone-mvn-settings
    settings:
      serverSecrets:
        from_secret: maven_server_secrets
  - name: deploy
    image: maven:3-jdk-8
    commands:
      - mvn deploy -B -s settings.xml

trigger:
  branch:
    - master
  event:
    exclude:
      - pull_request
    include:
      - push