kind: pipeline
name: publish
type: docker

steps:
  - name: create settings.xml
    image: md5lukas/drone-mvn-settings
    settings:
      serverSecrets:
        from_secret: maven_server_secrets
  - name: deploy
    image: maven:3-jdk-8
    commands:
      - mvn deploy -B -s settings.xml
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: target/md5-commons*
      checksum:
        - md5
        - sha256

trigger:
  event:
    exclude:
      - pull_request
    include:
      - tag
---
kind: pipeline
name: test only
type: docker

steps:
  - name: test
    image: maven:3-jdk-8
    commands:
      - mvn test -B

trigger:
  event:
    exclude:
      - tag
    include:
      - push